### PR TITLE
Game of Zones components

### PR DESCRIPTION
**Pull request by lovincyrus**
https://cosmos-ui-r647g5wxe.now.sh/?path=/story/gozpage--normal

Also, fixes https://github.com/allinbits/design/issues/236

### CODE REVIEW

**Comment by fadeev** [comment]
First iteration of Newsletter signup, Milestones and "Join the discussion" card components is done.

https://cosmos-ui-5yfoi12wz.now.sh/?path=/story/newslettersignup--normal
https://cosmos-ui-5yfoi12wz.now.sh/?path=/story/gozmilestones--normal
https://cosmos-ui-5yfoi12wz.now.sh/?path=/story/gozcard--normal

**Comment by fadeev** [comment]
Added `GozPage` component as an attempt at implementing a part of the page inside Storybook. I don't necessarily think that a whole page should be inside this repo, but as a testing ground it seems solid.

**Comment by fadeev** [comment]
@nassdonald you are right, we can use `fetch` to make requests, which will not open a new window. We cannot, however, trigger an error state, because fetch returns an `opaque` response. Every requests looks like "something may or may not have happened". Let me know should we handle state transition from `default` to `success`.

**Comment by fadeev** [comment]
`fetch` doesn't work for me any more, for some reason.

**Comment by nassdonald** [comment]
Oh that's interesting. So we can only show a success state and hope it all worked? What if someone goes offline and submits the form?

Transition-wise, I've been thinking of adding some motion patterns to our Design System, but just haven't had the time yet. So for now, let's just do a simple fade:
```
default state opacity 1 -> 0 @ 400ms linear
then
success state opacity 0 -> 1 @ 200ms linear
```

**Comment by fadeev** [comment]
Added a spinner, and I will be adding a transition between newsletter signup states now. After that I think we should merge, publish, make a page in cosmos.network and deploy.

**Comment by fadeev** [comment]
Okay, `fetch` works now, my mistake.

**Comment by fadeev** [comment]
Added a gap to Footer component to address https://github.com/allinbits/design/issues/236

Screenshot 2020-03-20 at 22 42 47

**Pull request merged**
