### PR TITLE
netlify -> now

### PR DESCRIPTION
**Pull request by lovincyrus**

### CODE REVIEW

**Comment by nassdonald** [comment]
Getting a 404 on the Deployment link here…

**Comment by lovincyrus** [comment]
> Getting a 404 on the Deployment link here…

https://zeit.co/aib/cosmos-ui/3ulrgp7x4

**Comment by nassdonald** [comment]
Yup, that link is 404 for me too.

**Comment by lovincyrus** [comment]
> Yup, that link is 404 for me too.

Sent you an invite on Slack.

**Comment by lovincyrus** [comment]
> > Getting a 404 on the Deployment link here…
> 
> https://zeit.co/aib/cosmos-ui/3ulrgp7x4

You should be able to view this link: https://cosmos-ui-3ulrgp7x4.now.sh

**Pull request merged**
