### PR TITLE
Stars

### PR DESCRIPTION
**Pull request by fadeev**
Thrown together a quick prototype so we can decide whether we want to go in this direction. Decided to stick with two dimensions for now. Background can be easily optimised by using a subdivided surface with vertices as particles, so it will run smooth in production.

https://deploy-preview-128--cosmos-ui.netlify.com/iframe.html?id=solarsystem--normal

cc @nassdonald @lovincyrus

### CODE REVIEW

**Comment by nassdonald** [comment]
This is amazing!! Very excited about this. 🤩

So this is all just SVG?

**Comment by nylira** [comment]
This looks amazing @fadeev! Straight from the video

**Comment by fadeev** [comment]
Thanks, guys! @nassdonald only hexes and logo, rest is shadows and positioning, which makes it a bit easier to dynamically add planets, orbits.

**Comment by fadeev** [comment]
Added a planet.

https://deploy-preview-128--cosmos-ui.netlify.com/iframe.html?id=planet--normal

Inspired by https://youtu.be/Eb8xkDi_PUg?t=21

**Comment by fadeev** [comment]
Added some blinking lights to the Cosmos classic background.

Screenshot 2020-01-26 at 21 17 58

https://deploy-preview-128--cosmos-ui.netlify.com/iframe.html?id=stars--normal

**Comment by nassdonald** [comment]
This is super cool!! 😍 I wonder if we can get them to pan slowly too? Would require looping the transform, right?

**Comment by fadeev** [comment]
@nassdonald Added a bit of parallax.

**Comment by fadeev** [comment]
We're not going to merge this branch, but I'm keeping it open for now in case we need to look at the code for planets and whatnot.

**Comment by nassdonald** [comment]
> We're not going to merge this branch

Good shout. Let's revisit once we have a clear idea of what we want for the visuals. With what I'm working on right now, I definitely think a lot of this will be usable with some tweaks here and there.

**Pull request merged**
