### PR TITLE
SectionSearch

### PR DESCRIPTION
**Pull request by fadeev**
Decided to start extracting components from the docs theme into this repo. I wonder if developing components outside of their "parent" projects will make them more reusable and reliable. Implicit dependencies are harmful.

Even this component, simple as it is, had some global state upon which it relied. Font family was inherited, `md` function for converting markdown, `this.$site` with global state and a couple of components (not explicitly imported, because VuePress imports all components by default).

Let's try to integrate Algolia in this component and then use it in the docs theme.

btw, can't figure out how to enable pug and stylus in Storybook, had to convert to HTML/CSS. Which may be a good thing, not sure if pug/stylus is necessarily the way forward.

Screenshot 2020-03-08 at 23 42 36

### CODE REVIEW

**Comment by nassdonald** [comment]
This is an interesting one. I wonder if we should strip it down so it doesn't necessarily have to come in side sheet form? 🤔 I can see future use cases for more 'slim' search UIs in other places. But perhaps we should just cross that bridge when it comes to it? 🤷‍♂ 

**Side note:** I didn't notice before, but the behavior of the keyboard navigation should be such that the focus is always maintained on the input field. This is fairly standard behavior for search UI, auto-complete/typeahead etc. Also, tabbing shouldn't cycle through the results. It should focus the next element after the search input (in this case, the "Cancel" button). 🙂

**Comment by fadeev** [comment]
Extracted "Shortcuts" and "No results" sections into separate components to make the parent more manageable as well as make storybook more story-like, when we have all different parts and states displayed at the same time.

Screenshot 2020-03-13 at 00 04 22

I think this is easier to test (visually).

**Comment by nassdonald** [comment]
Wonderful!

Another point: we should probably hide the keyboard shortcuts and replace with an empty state of some sort for < desktop. Since it's difficult to target devices with no keyboard, we should just set a reasonable min-width media query to catch most cases. Thoughts?

**Comment by fadeev** [comment]
Yes, that's a good point!

**Comment by fadeev** [comment]
Sweet. Yeah, we'll iterate on that. I just wanted to extract this component as it is right now and sensibly split it into manageable pieces.

**Comment by fadeev** [comment]
Merging. We can push additional fixes and improvements in a separate branch.

**Pull request merged**
