### PR TITLE
Cosmos components

### PR DESCRIPTION
**Pull request by fadeev**
Three components at varying stages of doneness (footer is well done, cards are medium rare, hero is rare). Mostly made to think about how to create components that have a good theming interface.

So far, the best solution seems to be the simplest one: prefixed CSS variables with default values. Each themable property of an element within a component has a value that references a global CSS variable and defaults to a "good enough" that makes a component usable without any extra styles applied. For example:

```css
.cards__item__h1 {
  font-size: var(--ds-h4-font-size, 1rem);
}
```

Chrome Dev Tools show clearly which variables affect which elements. CSS variables are also easily searchable in a text editor.

To override a value of a variable for a single instance of a component, use inline styles. Wrap this inside another component like `TmCards` to create a themed component (can be useful for buttons).

```html
<cards style="--ds-h4-font-size: 3rem"/>
```

I strongly prefer a system, where components are styled using a consistent specificity value (single class per element, `0-1-0`). Using two classes for theming, like `.ds.ds__h1` (`0-2-0`) works reliably only if you know that processing doesn't affect specificity (which if does, because for scoping your selector becomes something like `.cards__item__h1[data-v-******]`, `0-2-0`).

I think prefixed variables are great. I've made a simple footer like the one on `cosmos.network` and by tweaking a couple of global vars I can make it very similar to what we use on docs and reuse it there.

https://github.com/allinbits/design/issues/114
https://github.com/allinbits/design/issues/111
https://github.com/allinbits/design/issues/102

### CODE REVIEW

**Comment by nassdonald** [comment]
:100: for Cosmos components! Would you like feedback on the design side of implementation here, or just the code & architecture? I appreciate that this is still WIP, so I don't want to point out things you haven't implemented already? 🙂

**Comment by fadeev** [comment]
@nassdonald feedback on footer and cards. I was thinking we could use the same footer for cosmos, docs and maybe even tendermint (by theming it). Cards is just a versatile component we use heavily on cosmos.

**Comment by nassdonald** [comment]
That's a very good idea. We'll just need to ensure it is responsive independently from the viewport width. For example, because of the layout in the docs (with sidebar), there is less horizontal space for the footer, therefore the adaptive breakpoints (media queries based on viewport width) built into the component may be appropriate for the Cosmos website, but not the docs, or vice versa. As you know, this is a common pain point with screen-based media queries in CSS , so perhaps we need configuration in the component's options that determine these breakpoints per instance?

**Comment by fadeev** [comment]
@nassdonald yeah, I've spent many hours trying to implement it with grid to avoid queries altogether, but I don't think it's possible. I should say, however, that I haven't noticed any bugs even with a sidebar present.

**Comment by nassdonald** [comment]
Yeah grid can only help us so much here. Perhaps we can get away with a more 'defensive' approach that adapts based on the narrowest likely use (i.e. docs) and it'll just mean the full-width website version will stretch a little more before it adapts. Thoughts?

**Comment by fadeev** [comment]
@nassdonald That could work. I mean, right now it works good enough, I think.

**Comment by fadeev** [comment]
> LGTM. We should probably rename the `Normal` branch to `Default` 😅

`default` is a reserved word.

**Pull request merged**
